import React from 'react'
import Head from 'next/head'
import { AlephiumConnectButton, useWallet } from '@alephium/web3-react'

export default function Home() {
  const { connectionStatus } = useWallet()

  return (
    <>
      <div >
        <AlephiumConnectButton />
        <Head>
          <title>Token Faucet</title>
          <meta name="description" content="Generated by @alephium/cli init" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
      </div>
    </>
  )
}
