import React from 'react'
import Head from 'next/head'
import { AlephiumConnectButton, useWallet } from '@alephium/web3-react'
import Header from "@/src/components/Header/Header";
import Home from "../screens/Home/Home";

export default function Index() {
  const { connectionStatus } = useWallet()

  return (
    
      <div style={{color: "fuchsia", display: "flex", flex: 1, flexDirection: "column", width: "100vw", height: "100vh"}} >
        <Header />
        <Head>
          <title>Token Faucet</title>
          <meta name="description" content="Generated by @alephium/cli init" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <Home />
      </div>
    
  )
}
