/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as CreditWalletContractJson } from "../CreditWallet.ral.json";
import { getContractByCodeHash } from "./contracts";

import { RalphMap } from "@alephium/web3";

// Custom types for the contract
export namespace CreditWalletTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    creditWallet: {
      params: CallContractParams<{ recipient: Address; amount: bigint }>;
      result: CallContractResult<null>;
    };
    getBalance: {
      params: CallContractParams<{ address: Address }>;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    creditWallet: {
      params: SignExecuteContractMethodParams<{
        recipient: Address;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    getBalance: {
      params: SignExecuteContractMethodParams<{ address: Address }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];

  export type Maps = { balances?: Map<Address, bigint> };
}

class Factory extends ContractFactory<CreditWalletInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, []);
  }

  consts = { ErrorCodes: { InsufficientAmount: BigInt("0") } };

  at(address: string): CreditWalletInstance {
    return new CreditWalletInstance(address);
  }

  tests = {
    creditWallet: async (
      params: Omit<
        TestContractParams<
          never,
          { recipient: Address; amount: bigint },
          CreditWalletTypes.Maps
        >,
        "initialFields"
      >
    ): Promise<TestContractResult<null, CreditWalletTypes.Maps>> => {
      return testMethod(this, "creditWallet", params, getContractByCodeHash);
    },
    getBalance: async (
      params: Omit<
        TestContractParams<never, { address: Address }, CreditWalletTypes.Maps>,
        "initialFields"
      >
    ): Promise<TestContractResult<bigint, CreditWalletTypes.Maps>> => {
      return testMethod(this, "getBalance", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: {},
    asset?: Asset,
    address?: string,
    maps?: CreditWalletTypes.Maps
  ) {
    return this.stateForTest_(initFields, asset, address, maps);
  }
}

// Use this object to test and deploy the contract
export const CreditWallet = new Factory(
  Contract.fromJson(
    CreditWalletContractJson,
    "=6-2+8a=2-2+c4=13-1+e=159-1+c=40+7a7e0214696e73657274206174206d617020706174683a2000=128",
    "d37d081fa0086abb89f2488fa67fef3b059d9ea26c94f77821110595a6f5d831",
    []
  )
);

// Use this class to interact with the blockchain
export class CreditWalletInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  maps = {
    balances: new RalphMap<Address, bigint>(
      CreditWallet.contract,
      this.contractId,
      "balances"
    ),
  };

  async fetchState(): Promise<CreditWalletTypes.State> {
    return fetchContractState(CreditWallet, this);
  }

  view = {
    creditWallet: async (
      params: CreditWalletTypes.CallMethodParams<"creditWallet">
    ): Promise<CreditWalletTypes.CallMethodResult<"creditWallet">> => {
      return callMethod(
        CreditWallet,
        this,
        "creditWallet",
        params,
        getContractByCodeHash
      );
    },
    getBalance: async (
      params: CreditWalletTypes.CallMethodParams<"getBalance">
    ): Promise<CreditWalletTypes.CallMethodResult<"getBalance">> => {
      return callMethod(
        CreditWallet,
        this,
        "getBalance",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    creditWallet: async (
      params: CreditWalletTypes.SignExecuteMethodParams<"creditWallet">
    ): Promise<CreditWalletTypes.SignExecuteMethodResult<"creditWallet">> => {
      return signExecuteMethod(CreditWallet, this, "creditWallet", params);
    },
    getBalance: async (
      params: CreditWalletTypes.SignExecuteMethodParams<"getBalance">
    ): Promise<CreditWalletTypes.SignExecuteMethodResult<"getBalance">> => {
      return signExecuteMethod(CreditWallet, this, "getBalance", params);
    },
  };

  async multicall<Callss extends CreditWalletTypes.MultiCallParams[]>(
    ...callss: Callss
  ): Promise<CreditWalletTypes.MulticallReturnType<Callss>> {
    return (await multicallMethods(
      CreditWallet,
      this,
      callss,
      getContractByCodeHash
    )) as CreditWalletTypes.MulticallReturnType<Callss>;
  }
}
