/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { RunScriptResult, DeployContractExecutionResult } from "@alephium/cli";
import { NetworkId } from "@alephium/web3";
import {
  Donations,
  DonationsInstance,
  Ticket,
  TicketInstance,
  CreditWallet,
  CreditWalletInstance,
} from ".";
import { default as devnetDeployments } from "....deployments.deployments.devnet.json";

export type Deployments = {
  deployerAddress: string;
  contracts: {
    Donations: DeployContractExecutionResult<DonationsInstance>;
    Ticket: DeployContractExecutionResult<TicketInstance>;
    CreditWallet: DeployContractExecutionResult<CreditWalletInstance>;
  };
};

function toDeployments(json: any): Deployments {
  const contracts = {
    Donations: {
      ...json.contracts["Donations"],
      contractInstance: Donations.at(
        json.contracts["Donations"].contractInstance.address
      ),
    },
    Ticket: {
      ...json.contracts["Ticket"],
      contractInstance: Ticket.at(
        json.contracts["Ticket"].contractInstance.address
      ),
    },
    CreditWallet: {
      ...json.contracts["CreditWallet"],
      contractInstance: CreditWallet.at(
        json.contracts["CreditWallet"].contractInstance.address
      ),
    },
  };
  return {
    ...json,
    contracts: contracts as Deployments["contracts"],
  };
}

export function loadDeployments(
  networkId: NetworkId,
  deployerAddress?: string
): Deployments {
  const deployments = networkId === "devnet" ? devnetDeployments : undefined;
  if (deployments === undefined) {
    throw Error("The contract has not been deployed to the " + networkId);
  }
  const allDeployments: any[] = Array.isArray(deployments)
    ? deployments
    : [deployments];
  if (deployerAddress === undefined) {
    if (allDeployments.length > 1) {
      throw Error(
        "The contract has been deployed multiple times on " +
          networkId +
          ", please specify the deployer address"
      );
    } else {
      return toDeployments(allDeployments[0]);
    }
  }
  const result = allDeployments.find(
    (d) => d.deployerAddress === deployerAddress
  );
  if (result === undefined) {
    throw Error("The contract deployment result does not exist");
  }
  return toDeployments(result);
}
