/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as DonationsContractJson } from "../Donations.ral.json";
import { getContractByCodeHash } from "./contracts";

import { RalphMap } from "@alephium/web3";

// Custom types for the contract
export namespace DonationsTypes {
  export type State = Omit<ContractState<any>, "fields">;
  export type DonationEvent = ContractEvent<{
    donor: Address;
    recipient: Address;
    amount: bigint;
  }>;

  export interface CallMethodTable {
    depositTouser: {
      params: CallContractParams<{ recipient: Address; amount: bigint }>;
      result: CallContractResult<null>;
    };
    getDonorTotal: {
      params: CallContractParams<{ donor: Address }>;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    depositTouser: {
      params: SignExecuteContractMethodParams<{
        recipient: Address;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    getDonorTotal: {
      params: SignExecuteContractMethodParams<{ donor: Address }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];

  export type Maps = { donors?: Map<Address, bigint> };
}

class Factory extends ContractFactory<DonationsInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, []);
  }

  eventIndex = { Donation: 0 };
  consts = { ErrorCodes: { InsufficientAmount: BigInt("0") } };

  at(address: string): DonationsInstance {
    return new DonationsInstance(address);
  }

  tests = {
    depositTouser: async (
      params: Omit<
        TestContractParams<
          never,
          { recipient: Address; amount: bigint },
          DonationsTypes.Maps
        >,
        "initialFields"
      >
    ): Promise<TestContractResult<null, DonationsTypes.Maps>> => {
      return testMethod(this, "depositTouser", params, getContractByCodeHash);
    },
    getDonorTotal: async (
      params: Omit<
        TestContractParams<never, { donor: Address }, DonationsTypes.Maps>,
        "initialFields"
      >
    ): Promise<TestContractResult<bigint, DonationsTypes.Maps>> => {
      return testMethod(this, "getDonorTotal", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: {},
    asset?: Asset,
    address?: string,
    maps?: DonationsTypes.Maps
  ) {
    return this.stateForTest_(initFields, asset, address, maps);
  }
}

// Use this object to test and deploy the contract
export const Donations = new Factory(
  Contract.fromJson(
    DonationsContractJson,
    "=6-2+95=2-2+cf=13-1+5=165-1+c=40+7a7e0214696e73657274206174206d617020706174683a2000=144",
    "3e375ba16f5597393ea017c1ef8e3112281bd62f057e96fc842143b55fed3630",
    []
  )
);

// Use this class to interact with the blockchain
export class DonationsInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  maps = {
    donors: new RalphMap<Address, bigint>(
      Donations.contract,
      this.contractId,
      "donors"
    ),
  };

  async fetchState(): Promise<DonationsTypes.State> {
    return fetchContractState(Donations, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeDonationEvent(
    options: EventSubscribeOptions<DonationsTypes.DonationEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Donations.contract,
      this,
      options,
      "Donation",
      fromCount
    );
  }

  view = {
    depositTouser: async (
      params: DonationsTypes.CallMethodParams<"depositTouser">
    ): Promise<DonationsTypes.CallMethodResult<"depositTouser">> => {
      return callMethod(
        Donations,
        this,
        "depositTouser",
        params,
        getContractByCodeHash
      );
    },
    getDonorTotal: async (
      params: DonationsTypes.CallMethodParams<"getDonorTotal">
    ): Promise<DonationsTypes.CallMethodResult<"getDonorTotal">> => {
      return callMethod(
        Donations,
        this,
        "getDonorTotal",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    depositTouser: async (
      params: DonationsTypes.SignExecuteMethodParams<"depositTouser">
    ): Promise<DonationsTypes.SignExecuteMethodResult<"depositTouser">> => {
      return signExecuteMethod(Donations, this, "depositTouser", params);
    },
    getDonorTotal: async (
      params: DonationsTypes.SignExecuteMethodParams<"getDonorTotal">
    ): Promise<DonationsTypes.SignExecuteMethodResult<"getDonorTotal">> => {
      return signExecuteMethod(Donations, this, "getDonorTotal", params);
    },
  };

  async multicall<Callss extends DonationsTypes.MultiCallParams[]>(
    ...callss: Callss
  ): Promise<DonationsTypes.MulticallReturnType<Callss>> {
    return (await multicallMethods(
      Donations,
      this,
      callss,
      getContractByCodeHash
    )) as DonationsTypes.MulticallReturnType<Callss>;
  }
}
