/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as TicketContractJson } from "../Ticket.ral.json";
import { getContractByCodeHash } from "./contracts";

import { RalphMap } from "@alephium/web3";

// Custom types for the contract
export namespace TicketTypes {
  export type State = Omit<ContractState<any>, "fields">;
  export type TicketEvent = ContractEvent<{
    address: Address;
    success: boolean;
  }>;

  export interface CallMethodTable {
    buyTicket: {
      params: CallContractParams<{ address: Address; amount: bigint }>;
      result: CallContractResult<boolean>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    buyTicket: {
      params: SignExecuteContractMethodParams<{
        address: Address;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];

  export type Maps = { ticket?: Map<Address, boolean> };
}

class Factory extends ContractFactory<TicketInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, []);
  }

  eventIndex = { Ticket: 0 };

  at(address: string): TicketInstance {
    return new TicketInstance(address);
  }

  tests = {
    buyTicket: async (
      params: Omit<
        TestContractParams<
          never,
          { address: Address; amount: bigint },
          TicketTypes.Maps
        >,
        "initialFields"
      >
    ): Promise<TestContractResult<boolean, TicketTypes.Maps>> => {
      return testMethod(this, "buyTicket", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: {},
    asset?: Asset,
    address?: string,
    maps?: TicketTypes.Maps
  ) {
    return this.stateForTest_(initFields, asset, address, maps);
  }
}

// Use this object to test and deploy the contract
export const Ticket = new Factory(
  Contract.fromJson(
    TicketContractJson,
    "=6-2+71=13-1+a=138+7a7e0214696e73657274206174206d617020706174683a2000=24",
    "8ec61b10c99bc697af540886a926edffccde02233e12cfe45726c53b09d8b575",
    []
  )
);

// Use this class to interact with the blockchain
export class TicketInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  maps = {
    ticket: new RalphMap<Address, boolean>(
      Ticket.contract,
      this.contractId,
      "ticket"
    ),
  };

  async fetchState(): Promise<TicketTypes.State> {
    return fetchContractState(Ticket, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeTicketEvent(
    options: EventSubscribeOptions<TicketTypes.TicketEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Ticket.contract,
      this,
      options,
      "Ticket",
      fromCount
    );
  }

  view = {
    buyTicket: async (
      params: TicketTypes.CallMethodParams<"buyTicket">
    ): Promise<TicketTypes.CallMethodResult<"buyTicket">> => {
      return callMethod(
        Ticket,
        this,
        "buyTicket",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    buyTicket: async (
      params: TicketTypes.SignExecuteMethodParams<"buyTicket">
    ): Promise<TicketTypes.SignExecuteMethodResult<"buyTicket">> => {
      return signExecuteMethod(Ticket, this, "buyTicket", params);
    },
  };

  async multicall<Callss extends TicketTypes.MultiCallParams[]>(
    ...callss: Callss
  ): Promise<TicketTypes.MulticallReturnType<Callss>> {
    return (await multicallMethods(
      Ticket,
      this,
      callss,
      getContractByCodeHash
    )) as TicketTypes.MulticallReturnType<Callss>;
  }
}
